spring.application.name=ms-monitor-oracle
server.port=8080

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka-1:9092}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@jaaa0f5tn6flh4kw_tp?TNS_ADMIN=/app/wallet}
spring.datasource.username=User_CloudNative
spring.datasource.password=CloudNative123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

spring.jpa.properties.hibernate.jdbc.time_zone=America/Santiago
spring.jackson.time-zone=America/Santiago
