spring.application.name=ms-monitor-oracle
server.port=8083

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092,localhost:39092,localhost:49092}

spring.datasource.url=jdbc:oracle:thin:@jaaa0f5tn6flh4kw_tp?TNS_ADMIN=C:/Wallet_JAAA0F5TN6FLH4KW
spring.datasource.username=User_CloudNative
spring.datasource.password=CloudNative123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
